In [3]:
import torch
import math

# 定义 Q, K（与图片完全一致）
Q = torch.tensor([
    [-1.0,  2.0, -3.0],
    [ 4.0, -5.0,  6.0],
    [-7.0,  8.0, -9.0],
    [10.0, -11.0, 12.0]
])  # shape: (4, 3)

K = torch.tensor([
    [ 2.0, -1.0,  3.0],
    [-4.0,  5.0, -6.0],
    [ 7.0, -8.0,  9.0],
    [-10.0, 11.0, -12.0]
])  # shape: (4, 3)

V = torch.tensor([
    [ 1.0,  0.5, -0.5],
    [-1.0,  2.0,  3.0],
    [ 4.0, -2.0,  1.0],
    [ 0.0,  1.0, -1.0]
])  # shape: (4, 3)

d = Q.shape[1]  # d = 4

# QK^T
scores = Q @ K.T

# scaled dot-product
scaled_scores = scores / math.sqrt(d)

# softmax（按行）
attn = torch.softmax(scaled_scores, dim=-1)

output = attn @ V

print("QK^T =")
print(scores)

print("\nQK^T / sqrt(d) =")
print(scaled_scores)

print("\nsoftmax(QK^T / sqrt(d)) =")
print(attn)

print("softmax attention")
print(output)



QK^T =
tensor([[ -13.,   32.,  -50.,   68.],
        [  31.,  -77.,  122., -167.],
        [ -49.,  122., -194.,  266.],
        [  67., -167.,  266., -365.]])

QK^T / sqrt(d) =
tensor([[  -7.5056,   18.4752,  -28.8675,   39.2598],
        [  17.8979,  -44.4560,   70.4367,  -96.4175],
        [ -28.2902,   70.4367, -112.0060,  153.5752],
        [  38.6825,  -96.4175,  153.5752, -210.7328]])

softmax(QK^T / sqrt(d)) =
tensor([[4.8984e-21, 9.4050e-10, 2.5863e-30, 1.0000e+00],
        [1.5228e-23, 0.0000e+00, 1.0000e+00, 0.0000e+00],
        [0.0000e+00, 7.8241e-37, 0.0000e+00, 1.0000e+00],
        [0.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00]])
softmax attention
tensor([[-9.4050e-10,  1.0000e+00, -1.0000e+00],
        [ 4.0000e+00, -2.0000e+00,  1.0000e+00],
        [-7.8241e-37,  1.0000e+00, -1.0000e+00],
        [ 4.0000e+00, -2.0000e+00,  1.0000e+00]])


In [ ]:
我的算法好像出错了，应该先算QK^T / sqrt(d)，然后再求max和sum?